// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AfternoonswalController from "./afternoonswal_controller"
application.register("afternoonswal", AfternoonswalController)

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import DoggiesController from "./doggies_controller"
application.register("doggies", DoggiesController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MedicationsController from "./medications_controller"
application.register("medications", MedicationsController)

import MorningswalController from "./morningswal_controller"
application.register("morningswal", MorningswalController)

import NightswalController from "./nightswal_controller"
application.register("nightswal", NightswalController)

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)

import SwalController from "./swal_controller"
application.register("swal", SwalController)
