// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import DoggiesController from "./doggies_controller"
application.register("doggies", DoggiesController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MedicationsController from "./medications_controller"
application.register("medications", MedicationsController)

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)
