meta_product_name: "DocDoggie"
meta_title: "DocDoggie - A pawsome way to register your medication reminders!"
meta_description: "DocDoggie is the new app that will help you manage your daily medications in a more cheerful way, with a little doggie's help!"
meta_image: "doggies/cream-docdoggie.png" # should exist in `app/assets/images/`
